import { PageError, Source } from '../../html/parser';
import type { Node } from 'estree';
import { Scope } from './Scope';
import { Value } from './Value';

export const SPECIAL_ATTR_PREFIX = ':';
export const SCOPE_NAME_ATTR = 'aka';
export const CLASS_VALUE_ATTR_PREFIX = 'class-';
export const STYLE_VALUE_ATTR_PREFIX = 'style-';
export const EVENT_VALUE_ATTR_PREFIX = 'on-';
export const DID_VALUE_ATTR_PREFIX = 'did-';
export const WILL_VALUE_ATTR_PREFIX = 'will-';
export const TEXT_VALUE_PREFIX = 't$';
// compiled form of the ATTR prefixes above, as stored in Scope.values keys
export const CLASS_VALUE_PREFIX = 'class$';
export const STYLE_VALUE_PREFIX = 'style$';
export const EVENT_VALUE_PREFIX = 'on$';
export const DID_VALUE_PREFIX = 'did$';
export const WILL_VALUE_PREFIX = 'will$';
// `:for-each`/`:for-as`/`:for-key` are fixed (non-prefixed) attribute names,
// not open-ended `prefix-name` families like class-/style-/on-/did-/will-
export const FOR_EACH_ATTR = 'for-each';
export const FOR_AS_ATTR = 'for-as';
export const FOR_KEY_ATTR = 'for-key';
export const FOR_EACH_VALUE = 'for$each';
export const FOR_AS_VALUE = 'for$as';
export const FOR_KEY_VALUE = 'for$key';
// the per-item value's runtime key defaults to this (`:for-as` overrides it);
// it's compiled as an ordinary value, not a `for$`-prefixed one, so bare
// `${data}` references qualify to `this.data` with no special-casing needed
export const FOR_DATA_DEFAULT_NAME = 'data';

export class Page {
  source: Source;
  global: Scope;
  defines: Map<string, Scope>;
  values: Map<string, Value>;
  main?: Scope;
  errors: PageError[] = [];
  nextValueId = 0;
  nextScopeId = 0;
  /** the `CoreScopeProps`-shaped ObjectExpression AST generated by stage7, if it ran */
  propsAST?: Node;
  /** `propsAST` serialized to JS source via escodegen */
  propsString?: string;

  constructor(source: Source, global?: Scope) {
    this.source = source;
    this.global = global ?? new Scope(this);
    if (global) {
      global.page = this;
    }
    this.defines = new Map();
    this.values = new Map();
  }

  createValueId() {
    return `v${this.nextValueId++}`;
  }

  createScopeId() {
    return `s${this.nextScopeId++}`;
  }
}
