import { PageError, Source } from '../../html/parser';
import type { Node } from 'estree';
import { DIRECTIVE_TAG_PREFIX } from '../../html/dom';
import { Scope } from './Scope';
import { Value } from './Value';

export const SPECIAL_ATTR_PREFIX = ':';
export const SCOPE_NAME_ATTR = 'aka';
export const CLASS_VALUE_ATTR_PREFIX = 'class-';
export const STYLE_VALUE_ATTR_PREFIX = 'style-';
export const EVENT_VALUE_ATTR_PREFIX = 'on-';
export const DID_VALUE_ATTR_PREFIX = 'did-';
export const WILL_VALUE_ATTR_PREFIX = 'will-';
export const TEXT_VALUE_PREFIX = 't$';
// compiled form of the ATTR prefixes above, as stored in Scope.values keys
export const CLASS_VALUE_PREFIX = 'class$';
export const STYLE_VALUE_PREFIX = 'style$';
export const EVENT_VALUE_PREFIX = 'on$';
export const DID_VALUE_PREFIX = 'did$';
export const WILL_VALUE_PREFIX = 'will$';
// `:for-each`/`:for-as`/`:for-key` are fixed (non-prefixed) attribute names,
// not open-ended `prefix-name` families like class-/style-/on-/did-/will-
export const FOR_EACH_ATTR = 'for-each';
export const FOR_AS_ATTR = 'for-as';
export const FOR_KEY_ATTR = 'for-key';
export const FOR_EACH_VALUE = 'for$each';
export const FOR_AS_VALUE = 'for$as';
export const FOR_KEY_VALUE = 'for$key';
// the per-item value's runtime key defaults to this (`:for-as` overrides it);
// it's compiled as an ordinary value, not a `for$`-prefixed one, so bare
// `${data}` references qualify to `this.data` with no special-casing needed
export const FOR_DATA_DEFAULT_NAME = 'data';
// <:define tag="custom-name:base-tag" ...> declares a custom tag; parser
// uppercases tag names, matching how preprocessor.ts's own directive tags
// (IMPORT_DIRECTIVE_TAG etc.) are spelled
export const DEFINE_DIRECTIVE_TAG = DIRECTIVE_TAG_PREFIX + 'DEFINE';
export const DEFINE_TAG_ATTR = 'tag';
// internal-only marker stamped on a <:define>'s expanded inner element
// during stage1-load's pre-pass, so the element can be matched back up to
// its custom tag name once its own scope is created; stripped before that
// scope's element is otherwise treated like any other
export const DEFINE_NAME_MARKER = 'data-markout-define';

export class Page {
  source: Source;
  global: Scope;
  defines: Map<string, Scope>;
  /** custom tag name -> its <:define> scope, populated by stage1-load */
  customTags: Map<string, Scope>;
  /** the <:define> scopes themselves -- excluded from their parent's
   * compiled children by stage7-generate, since they're never live at
   * their own natural position, only instantiated per usage site */
  definitionScopes: Set<Scope>;
  values: Map<string, Value>;
  main?: Scope;
  errors: PageError[] = [];
  nextValueId = 0;
  nextScopeId = 0;
  /** the `CoreScopeProps`-shaped ObjectExpression AST generated by stage7, if it ran */
  propsAST?: Node;
  /** `propsAST` serialized to JS source via escodegen */
  propsString?: string;

  constructor(source: Source, global?: Scope) {
    this.source = source;
    this.global = global ?? new Scope(this);
    if (global) {
      global.page = this;
    }
    this.defines = new Map();
    this.customTags = new Map();
    this.definitionScopes = new Set();
    this.values = new Map();
  }

  createValueId() {
    return `v${this.nextValueId++}`;
  }

  createScopeId() {
    return `s${this.nextScopeId++}`;
  }
}
